exports.pool = {
    legendary : [
        "SKYN **LEGENDARY** Debug mode", 
        "SKYN **LEGENDARY** S.U.R - PRIZE MACHINE"
    ],

    rare : [
        "SKYN *RARE* Banana L", 
        "SKYN *RARE* Banana R", 
        "SKYN *RARE* Beauty Mask - Blue", 
        "SKYN *RARE* Beauty Mask - Green", 
        "SKYN *RARE* Beauty Mask - Pink", 
        "SKYN *RARE* Beauty Mask - Purple", 
        "SKYN *RARE* Beauty Mask - White", 
        "SKYN *RARE* Beauty Mask - Yellow", 
        "SKYN *RARE* Chamomile Tea L - Blue", 
        "SKYN *RARE* Chamomile Tea L - Dark", 
        "SKYN *RARE* Chamomile Tea L - Green", 
        "SKYN *RARE* Chamomile Tea L - Orange", 
        "SKYN *RARE* Chamomile Tea L - Pink", 
        "SKYN *RARE* Chamomile Tea L - Plain", 
        "SKYN *RARE* Chamomile Tea L - Purple", 
        "SKYN *RARE* Chamomile Tea L - Red", 
        "SKYN *RARE* Chamomile Tea L - Teal", 
        "SKYN *RARE* Chamomile Tea L - Yellow", 
        "SKYN *RARE* Chamomile Tea R - Blue", 
        "SKYN *RARE* Chamomile Tea R - Dark", 
        "SKYN *RARE* Chamomile Tea R - Green", 
        "SKYN *RARE* Chamomile Tea R - Orange", 
        "SKYN *RARE* Chamomile Tea R - Pink", 
        "SKYN *RARE* Chamomile Tea R - Plain", 
        "SKYN *RARE* Chamomile Tea R - Purple", 
        "SKYN *RARE* Chamomile Tea R - Red", 
        "SKYN *RARE* Chamomile Tea R - Teal", 
        "SKYN *RARE* Chamomile Tea R - Yellow", 
        "SKYN *RARE* Coffee L - Blue/Red", 
        "SKYN *RARE* Coffee L - Dark", 
        "SKYN *RARE* Coffee L - Green/Orange", 
        "SKYN *RARE* Coffee L - Orange/Green", 
        "SKYN *RARE* Coffee L - Pink/Teal", 
        "SKYN *RARE* Coffee L - Plain", 
        "SKYN *RARE* Coffee L - Purple/Yellow", 
        "SKYN *RARE* Coffee L - Red/Blue", 
        "SKYN *RARE* Coffee L - Teal/Pink", 
        "SKYN *RARE* Coffee L - Yellow/Purple", 
        "SKYN *RARE* Coffee R - Blue/Yellow", 
        "SKYN *RARE* Coffee R - Dark", 
        "SKYN *RARE* Coffee R - Green/Purple", 
        "SKYN *RARE* Coffee R - Orange/Pink", 
        "SKYN *RARE* Coffee R - Pink/Orange", 
        "SKYN *RARE* Coffee R - Plain", 
        "SKYN *RARE* Coffee R - Purple/Red", 
        "SKYN *RARE* Coffee R - Red/Teal", 
        "SKYN *RARE* Coffee R - Teal/Green", 
        "SKYN *RARE* Coffee R - Yellow/Blue", 
        "SKYN *RARE* Salad -  Yellow Bowl", 
        "SKYN *RARE* Salad - Blue Bowl", 
        "SKYN *RARE* Salad - Clear Bowl", 
        "SKYN *RARE* Salad - Green Bowl", 
        "SKYN *RARE* Salad - Orange Bowl", 
        "SKYN *RARE* Salad - Pink Bowl", 
        "SKYN *RARE* Salad - Purple Bowl", 
        "SKYN *RARE* Salad - Red Bowl", 
        "SKYN *RARE* Salad - Teal Bowl", 
        "SKYN *RARE* Salad -Dark Bowl", 
        "SKYN *RARE* Squats!"
    ],

    common : [ 
        "SKYN - AVEAUX 'CA 'DEUX - Energy Drink L", 
        "SKYN - AVEAUX 'CA 'DEUX - Energy Drink R", 
        "SKYN - BERRY BLISS - Energy Drink L", 
        "SKYN - BERRY BLISS - Energy Drink R", 
        "SKYN - CUTIE FRUITIE - Energy Drink L", 
        "SKYN - CUTIE FRUITIE - Energy Drink R", 
        "SKYN - FIZZY FLAME - Energy Drink L", 
        "SKYN - FIZZY FLAME - Energy Drink R", 
        "SKYN - PEACH POWER - Energy Drink L", 
        "SKYN - PEACH POWER - Energy Drink R", 
        "SKYN - SHARK ENERGY - Energy Drink L", 
        "SKYN - SHARK ENERGY - Energy Drink R", 
        "SKYN - THROAT COAT - Energy Drink L", 
        "SKYN - THROAT COAT - Energy Drink R", 
        "SKYN - VEIN POP - Energy Drink L", 
        "SKYN - VEIN POP - Energy Drink R", 
        "SKYN - VIRAL SLUDGE - Energy Drink L", 
        "SKYN - VIRAL SLUDGE - Energy Drink R", 
        "SKYN Dumbbell L Pastel Blue", 
        "SKYN Dumbbell L Pastel Green", 
        "SKYN Dumbbell L Pastel Orange", 
        "SKYN Dumbbell L Pastel Pink", 
        "SKYN Dumbbell L Pastel Purple", 
        "SKYN Dumbbell L Pastel Red", 
        "SKYN Dumbbell L Pastel Teal", 
        "SKYN Dumbbell L Pastel Yellow", 
        "SKYN Dumbbell L Vibrant Blue", 
        "SKYN Dumbbell L Vibrant Green", 
        "SKYN Dumbbell L Vibrant Orange", 
        "SKYN Dumbbell L Vibrant Pink", 
        "SKYN Dumbbell L Vibrant Purple", 
        "SKYN Dumbbell L Vibrant Red", 
        "SKYN Dumbbell L Vibrant Teal", 
        "SKYN Dumbbell L Vibrant Yellow", 
        "SKYN Dumbbell R Pastel Blue", 
        "SKYN Dumbbell R Pastel Green", 
        "SKYN Dumbbell R Pastel Orange", 
        "SKYN Dumbbell R Pastel Pink", 
        "SKYN Dumbbell R Pastel Purple", 
        "SKYN Dumbbell R Pastel Red", 
        "SKYN Dumbbell R Pastel Teal", 
        "SKYN Dumbbell R Pastel Yellow", 
        "SKYN Dumbbell R Vibrant Blue", 
        "SKYN Dumbbell R Vibrant Green", 
        "SKYN Dumbbell R Vibrant Orange", 
        "SKYN Dumbbell R Vibrant Pink", 
        "SKYN Dumbbell R Vibrant Purple", 
        "SKYN Dumbbell R Vibrant Red", 
        "SKYN Dumbbell R Vibrant Teal", 
        "SKYN Dumbbell R Vibrant Yellow", 
        "SKYN HUD Colour Theme - Pastel Blue", 
        "SKYN HUD Colour Theme - Pastel Green", 
        "SKYN HUD Colour Theme - Pastel Orange", 
        "SKYN HUD Colour Theme - Pastel Pink", 
        "SKYN HUD Colour Theme - Pastel Purple", 
        "SKYN HUD Colour Theme - Pastel Red", 
        "SKYN HUD Colour Theme - Pastel Teal", 
        "SKYN HUD Colour Theme - Pastel Yellow", 
        "SKYN HUD Colour Theme - Vibrant Blue", 
        "SKYN HUD Colour Theme - Vibrant Green", 
        "SKYN HUD Colour Theme - Vibrant Orange", 
        "SKYN HUD Colour Theme - Vibrant Pink", 
        "SKYN HUD Colour Theme - Vibrant Purple", 
        "SKYN HUD Colour Theme - Vibrant Red", 
        "SKYN HUD Colour Theme - Vibrant Teal", 
        "SKYN HUD Colour Theme - Vibrant Yellow", 
        "SKYN Pimples - Extreme", 
        "SKYN Pimples - Extreme+Body", 
        "SKYN Pimples - Face+Body", 
        "SKYN Pimples - Forehead", 
        "SKYN Pimples - Forehead+Body", 
        "SKYN Pimples - T-Zone", 
        "SKYN Pimples - T-Zone+Body", 
        "SKYN Tired 1.0 - Black", 
        "SKYN Tired 1.0 - Blue", 
        "SKYN Tired 1.0 - Earthy", 
        "SKYN Tired 1.0 - Gray", 
        "SKYN Tired 1.0 - Red", 
        "SKYN Water Bottle L Blue", 
        "SKYN Water Bottle L Clear", 
        "SKYN Water Bottle L Pink", 
        "SKYN Water Bottle L Purple", 
        "SKYN Water Bottle L Red", 
        "SKYN Water Bottle L Teal", 
        "SKYN Water Bottle L Yellow", 
        "SKYN Water Bottle R Blue", 
        "SKYN Water Bottle R Clear", 
        "SKYN Water Bottle R Green", 
        "SKYN Water Bottle R Orange", 
        "SKYN Water Bottle R Pink", 
        "SKYN Water Bottle R Purple", 
        "SKYN Water Bottle R Red", 
        "SKYN Water Bottle R Teal", 
        "SKYN Water Bottle R Yellow", 
        "SKYN Water Bottle L Green", 
        "SKYN Water Bottle L Orange"
    ]
}